## Append samples of your project ##
resources:
- airunway_v1alpha1_modeldeployment.yaml
- airunway_v1alpha1_modeldeployment_llmd.yaml
- airunway_v1alpha1_inferenceproviderconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
